### ISSUE TITLE
Short description wording?

### ISSUE THREAD

**Issue by dajare** [cornetth/william-craft_ellen-craft_running-a-thousand-miles-for-freedom#2]
I learn a lot from others' productions, so take a look repos being reviewed from time to time. 

I noticed the short description ends: "`...and his slave.`", but shouldn't that read "`...and her slave.`"? Just thought I'd check!

David / Fife, UK

**Comment by cornetth** [comment]
It is not a typo. Ellen Craft posed as a man during their escape.

**Comment by dajare** [comment]
Suitably confusing! :man_shrugging: Thanks for the reply.
